Repository CMU-17313Q/fall23-nodebb-nirvana, pull requests merged in 2023-10, with the labels that each got.

#48 added test for anonymous icon
  test/template-helpers.js
Labels: testing

#49 Finished testing for post editing
  src/types/index.js
  test/posts.js
Labels: documentation, testing

#50 added test cases for user registration testing
  test/user.js
Labels: testing

#53 Finish Tests for Posting Private Post
  test/topics.js
Labels: bug, documentation, testing

#55 Revert "Finished Tests for Posting Private Post "
  node_modules/nodebb-plugin-composer-default/.eslintrc
  node_modules/nodebb-plugin-composer-default/.gitattributes
  node_modules/nodebb-plugin-composer-default/.jshintrc
  node_modules/nodebb-plugin-composer-default/LICENSE
  node_modules/nodebb-plugin-composer-default/README.md
  node_modules/nodebb-plugin-composer-default/controllers.js
  node_modules/nodebb-plugin-composer-default/library.js
  node_modules/nodebb-plugin-composer-default/package.json
  node_modules/nodebb-plugin-composer-default/plugin.json
  node_modules/nodebb-plugin-composer-default/screenshots/desktop.png
  node_modules/nodebb-plugin-composer-default/screenshots/mobile.png
  node_modules/nodebb-plugin-composer-default/static/less/composer.less
  node_modules/nodebb-plugin-composer-default/static/less/medium.less
  node_modules/nodebb-plugin-composer-default/static/less/page-compose.less
  node_modules/nodebb-plugin-composer-default/static/less/textcomplete.less
  node_modules/nodebb-plugin-composer-default/static/less/zen-mode.less
  node_modules/nodebb-plugin-composer-default/static/lib/.eslintrc
  node_modules/nodebb-plugin-composer-default/static/lib/admin.js
  node_modules/nodebb-plugin-composer-default/static/lib/client.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/autocomplete.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/categoryList.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/controls.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/drafts.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/formatting.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/preview.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/resize.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/scheduler.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/tags.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/uploads.js
  node_modules/nodebb-plugin-composer-default/static/templates/admin/plugins/composer-default.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/compose.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/composer.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/modals/topic-scheduler.tpl
  node_modules/nodebb-plugin-composer-default/websockets.js
Labels: bug

#54 User Guide Documentation
  UserGuide.md
Labels: documentation

#57 Github Actions for mongodb and postgres
  .github/workflows/test.yaml
  public/openapi/write/posts/pid.yaml
Labels: bug, documentation

#58 Updating docs
  public/openapi/write/posts/pid.yaml
Labels: documentation
