Repository CMU-17313Q/fall23-nodebb-nirvana, pull requests merged in 2023-09, with the labels that each got.

#31 editied footer - removed node branding (powered by)
  install/data/footer.json
Labels: enhancement, frontend

#42 add post anon testing
  test/posts.js
Labels: backend, testing

#44 Adding missing packages
  install/package.json
Labels: bug

#46 added the private button on the composer
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/composer.tpl
  src/types/index.js
Labels: enhancement, frontend

#47 finished testing for topic anonymization
  src/topics/create.js
  test/categories.js
  test/topics.js
Labels: testing
